language: cpp

_aliases:
  before_script_common: &before_script_common
    - curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install clang-8 lld-8 binutils-dev libboost-all-dev -y
    - sudo mv /usr/bin/ld /usr/bin/ld.old && sudo ln -s /usr/bin/lld-8 /usr/bin/ld

  env_common: &env_common
    - CC=clang-8
    - CXX=clang++-8
    - CC_FOR_BUILD=clang-8
    - CXX_FOR_BUILD=clang++-8
    - LD=lld-8

matrix:
  include:
    - name: "Compilation"
      os: linux
      compiler: clang
      dist: bionic
      env: *env_common
      before_script: *before_script_common
      script:
        - sudo mv /usr/bin/ld /usr/bin/ld.old && sudo ln -s /usr/bin/lld-8 /usr/bin/ld
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j4

    - name: "clang-format"
      os: linux
      compiler: clang
      dist: bionic
      env: *env_common
      before_script: *before_script_common
      script:
        - ./tools/format/run-clang-format.py -r src example tests

    - name: "clang-tidy"
      os: linux
      compiler: clang
      dist: bionic
      env: *env_common
      before_script: *before_script_common
      script:
        - sudo ln -s /usr/bin/clang-tidy-8 /usr/bin/clang-tidy
        - sudo ln -s /usr/bin/clang-apply-replacements-8 /usr/bin/clang-apply-replacements
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - cd ..
        - ./tools/tidy/tidy.py -c build/compile_commands.json -d src

    - name: "Tests ASAN"
      os: linux
      compiler: clang
      dist: bionic
      env: *env_common
      before_script: *before_script_common
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DKVS_TESTS_ASAN=ON ..
        - make -j4
        - ./tests/kvs-tests

    - name: "Tests TSAN"
      os: linux
      compiler: clang
      dist: bionic
      env: *env_common
      before_script: *before_script_common
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DKVS_TESTS_TSAN=ON ..
        - make -j4
        - ./tests/kvs-tests

    - name: "Load test utility ASAN"
      os: linux
      compiler: clang
      dist: bionic
      env: *env_common
      before_script: *before_script_common
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DKVS_TESTS_ASAN=ON ..
        - make -j4
        - ./load_test/kvs-load-test --cacheSize=33554432 --recordSize=1024 --maxNodes=20 --reads=1000 --writes=70 --deletes=70 --mounts=1 --unmounts=1 --krqs=1 --testTime=5000 --window=1000 --keyLength=8 --rndSeed=0 --dataSize=100 --threads=4

    - name: "Load test utility TSAN"
      os: linux
      compiler: clang
      dist: bionic
      env: *env_common
      before_script: *before_script_common
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DKVS_TESTS_TSAN=ON ..
        - make -j4
        - ./load_test/kvs-load-test --cacheSize=33554432 --recordSize=1024 --maxNodes=20 --reads=1000 --writes=70 --deletes=70 --mounts=1 --unmounts=1 --krqs=1 --testTime=5000 --window=1000 --keyLength=8 --rndSeed=0 --dataSize=100 --threads=4
